### ISSUE TITLE
Patch Tester 4.0.0 Beta 2 - Apply not working on J4

### ISSUE THREAD

**Issue by anibalsanchez** [joomla-extensions/patchtester#250] opened 2019-11-15 19:07 UTC
#### Steps to reproduce the issue

If you try to Apply, it always shows an error about not being able to rename a file.

**The previous version Patch Tester 3.0.0 Beta 4 works OK.** 

#### Expected result

Apply should work OK

#### Actual result

Fails with an error about renaming files

#### System information (as much as possible)

Latest J4 build and Patch Tester 4.0.0 Beta 2

#### Additional comments

Please, remove the Patch Tester 4.0.0 Beta from releases until it works OK. At the PBF events, the issue generates a lot of confusion.

**Comment by richard67** [comment] 2019-11-27 20:57
@anibalsanchez If your host is a Linux and not a Windows, your issue is already solved by PR #242 . It is merged already, only a new beta release has not been made yet. Other issues have also been solved with PR's since the last 4.0 Beta.

**Comment by richard67** [comment] 2019-11-27 20:59
@anibalsanchez P.S.: Please verify if PR #242 solves your issue, and if so, close it.

**Comment by N6REJ** [comment] 2020-01-26 04:25
I can't get 3 or 4 to work on 4.0 now

**Comment by richard67** [comment] 2020-01-27 11:54
@N6REJ PHP 7.4? If so: Does #252 solve it?

**Comment by N6REJ** [comment] 2020-01-27 17:03
> @N6REJ PHP 7.4? If so: Does #252 solve it?

I think you mean #242

**Comment by richard67** [comment] 2020-01-27 17:54
No I meant 252 in case if you have PHP 7.4. 252 solves issue with PHP 7.4, 242 has nothing to do with PHP 7.4.

**Comment by N6REJ** [comment] 2020-01-28 02:08
> No I meant 252 in case if you have PHP 7.4. 252 solves issue with PHP 7.4, 242 has nothing to do with PHP 7.4.

ok, but I seem to be able to apply without doing #252

**Comment by sakiss** [comment] 2020-02-11 15:46
I cannot get it to work, even with that patch.

I am getting the renaming exception mentioned above and if i chmod all the files to 777, then i am getting "There are no files to patch from this pull request. "

![Joomla  Patch Tester   4 0 dev site   Administration](https://user-images.githubusercontent.com/1838041/74252476-6c3fae80-4cf6-11ea-8e20-49bbea4e0451.png)

**Comment by roland-d** [comment] 2020-04-13 09:33
With the new release, this should all work again. Other users have used it without problems. So I am going to close this for now. If the issue is still present, feel free to re-open and we take a look at it.

**Closed by roland-d** 2020-04-13 09:33 UTC
