### ISSUE TITLE
Not working with Github credentials

### ISSUE THREAD

**Issue by jamgit** [joomla-extensions/patchtester#50] opened 2014-11-01 20:45 UTC
The error after putting in credentials on a local install using Mamp on a Mac with latest Joomla testing version of Joomla:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

**Comment by mbabker** [comment] 2015-02-23 02:03
I'm gonna close this as an external dependency.  It's either a bug in the JGithub, JHttp, or JUri classes (or somewhere else in the CMS API perhaps).

**Closed by mbabker** 2015-02-23 02:03 UTC

**Comment by roland-d** [comment] 2015-02-23 05:54
I had a PR (https://github.com/joomla/joomla-cms/pull/3387) once upon a time to fix this issue and I think it should still be fixed. It costs people a lot of time to figure out it is actually their password or username with the @ symbol that doesn't make Patchtester work.

The fix is in the how the authorization is passed as shown in this file:
https://github.com/joomla/joomla-cms/pull/3387/files#diff-e7bfabaeed9aaf4d928b3a1524107c50

I would like to ask to have another look or if you want me to do so, I can.

**Comment by mbabker** [comment] 2015-02-23 06:12
I think that PR just works around the root issue.  Unless it really is specific to GitHub, you should be able to hit the same problem using any of the other social packages (JMediawiki is another one using a username/password authentication) and the same failure there tells me the problem is in a common dependency between the two.  Now that I have my IDE open again, I'd say take a look into JUri (and now the Framework classes it extends) as both call `$uri->setPass()`.
